# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - rede  

  node:
    depends_on: 
      - db
    build:
      context: .
      dockerfile: Dockerfile.node
    ports: 
      - 3000:3000  
    networks:
      - rede 

networks:
  rede:
    driver: bridge  